spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always # auto-run schema.sql when a DataSource is configured
  profiles:
    default: prod # Default to prod if no other profile is active
  
  # Cache configuration - can be disabled with SPRING_CACHE_TYPE=none
  cache:
    type: ${SPRING_CACHE_TYPE:caffeine} # Defaulting to Caffeine for L1 in-memory cache
    cache-names: books,bookCovers,searchResults,bookRequests,searchRequests,bookSearchResults,nytBestsellersCurrent
    caffeine:
      spec: "maximumSize=1000,expireAfterWrite=240m,recordStats" # Default spec for all caches
  

  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: "/**"
      cache:
        cachecontrol:
          max-age: 365d # Cache versioned resources for 1 year
        # For unversioned resources, it can also set a shorter cache period
        # period: 7d 
        # use-cache-control-header: true # Ensure Cache-Control header is used

  codec: # Correctly nested under spring
    max-in-memory-size: 10MB # Configure global max buffer size for WebClient

app:
  security:
    admin:
      password: ${APP_ADMIN_PASSWORD}
    user:
      password: ${APP_USER_PASSWORD}
    headers:
      content-security-policy:
        enabled: true
  cache:
    enabled: true
    book: # Corresponds to app.redis.cache.book.ttl
      ttl: 24h # Default TTL for book cache entries
  cover-cache:
    dir: book-covers # Directory name for serving cached cover images
  book:
    covers:
      cdn-domain: ${S3_CDN_URL:https://book-finder.sfo3.digitaloceanspaces.com}
      additional-domains: ${BOOK_COVERS_ADDITIONAL_DOMAINS:}
  clicky:
    enabled: ${CLICKY_ENABLED:true}
    site-id: ${CLICKY_SITE_ID:101484793}
  
  # External embedding service URL (optional)
  # If not provided, a simple placeholder embedding will be used
  embedding:
    service:
      url: ${EMBEDDING_SERVICE_URL:}

# S3 configuration
s3:
  enabled: ${S3_ENABLED:false}
  access-key-id: ${S3_ACCESS_KEY_ID:}
  secret-access-key: ${S3_SECRET_ACCESS_KEY:}
  server-url: ${S3_SERVER_URL:}
  region: ${AWS_REGION:us-west-2}
  bucket-name: ${S3_BUCKET:}
  cdn-url: ${S3_CDN_URL:}
      
# Server configuration (common, can be overridden by application.properties or profiles)
server:
  port: ${SERVER_PORT:8095} # Default from YML, application.properties will override if SERVER_PORT is set
  compression:
    enabled: true
  
# Google Books API configuration
google:
  books:
    api:
      key: ${GOOGLE_BOOKS_API_KEY:}
      base-url: ${GOOGLE_BOOKS_API_BASE_URL:https://www.googleapis.com/books/v1}

# New York Times API configuration
nyt:
  api:
    base-url: ${NYT_API_BASE_URL:https://api.nytimes.com/svc/books/v3}
    key: ${NYT_API_KEY:}

# OpenLibrary API configuration
openlibrary:
  data:
    api:
      url: ${OPENLIBRARY_API_URL:https://openlibrary.org}

# Sitemap S3 configuration
sitemap:
  s3:
    accumulated-ids-key: sitemap/accumulated-book-ids.json

# Common Logging (can be overridden by profiles)
logging:
  level:
    root: INFO # Default root level
    "[com.williamcallahan.book_recommendation_engine]": INFO
    "[org.springframework.cache]": WARN
    "[org.hibernate]": WARN

---
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  # Dev-specific cache configuration
  cache:
    caffeine:
      spec: "maximumSize=1000,expireAfterWrite=240m,recordStats" # Dev cache settings
logging:
  level:
    '[org.springframework.boot.devtools]': WARN  # suppress DevTools internal logs
    "[org.springframework.web]": INFO # Changed from DEBUG
app:
  environment:
    mode: development # Custom property for dev mode
  security:
    admin:
      password: ${APP_ADMIN_PASSWORD:devAdminPass}
    user:
      password: ${APP_USER_PASSWORD:devUserPass}

---
spring:
  config:
    activate:
      on-profile: prod
  # Production-specific cache configuration with optimized settings
  cache:
    cache-names: books,bookSearchResults,nytBestsellersCurrent
    caffeine:
      spec: "maximumSize=2000,expireAfterWrite=12h,recordStats" # Optimized for production
logging:
  level:
    "[com.williamcallahan.book_recommendation_engine]": INFO # Standard INFO level for prod
app:
  environment:
    mode: production # Custom property for prod mode

---
spring:
  config:
    activate:
      on-profile: test
  cache:
    type: simple
logging:
  level:
    root: WARN
    "[com.williamcallahan.book_recommendation_engine]": INFO
    "[org.springframework]": WARN
s3:
  cdn-url: https://book-finder.sfo3.digitaloceanspaces.com
app:
  cache:
    enabled: true
