# Development profile configuration
spring:
  sql:
    init:
      mode: never # Disabled - schema managed manually in PostgreSQL
  jpa:
    hibernate:
      ddl-auto: validate # Validate schema against entities
    show-sql: true # Show SQL queries in console for debugging