# =============================================================================
# DEVELOPMENT PROFILE OVERRIDES
# =============================================================================
# This file provides development-specific overrides that make local development
# more convenient. These settings are MORE PERMISSIVE than production defaults.
# Use this profile for local development only: --spring.profiles.active=dev
# =============================================================================

spring:
  sql:
    init:
      mode: never # Schema managed manually in PostgreSQL (consistent across all envs)
  
  jpa:
    hibernate:
      ddl-auto: validate # Validate schema against entities (never auto-create)
    show-sql: true # DEV OVERRIDE: Show SQL queries in console for debugging

app:
  features:
    external-fallback:
      enabled: false # Disable external API fallbacks in local dev
